### ISSUE TITLE
tiny和aishell，训练报错

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSpeech#525]
### bash run.sh

============  Configuration Arguments ============
alpha_from: 1.0
alpha_to: 3.2
batch_size: 128
beam_size: 500
beta_from: 0.1
beta_to: 0.45
cutoff_prob: 1.0
cutoff_top_n: 40
error_rate_type: wer
lang_model_path: /root/DeepSpeech/examples/tiny/../..//models/lm/common_crawl_00.prune01111.trie.klm
mean_std_path: data/mean_std.npz
model_path: /root/DeepSpeech/examples/tiny/../..//models/librispeech
num_alphas: 45
num_batches: -1
num_betas: 8
num_conv_layers: 2
num_proc_bsearch: 12
num_rnn_layers: 3
rnn_layer_size: 2048
share_rnn_weights: 1
specgram_type: linear
trainer_count: 8
tune_manifest: data/manifest.dev-clean
use_gpu: 1
use_gru: 0
vocab_path: data/vocab.txt
================================================----
2021-02-18 12:11:32,090-INFO: begin to initialize the external scorer for decoding
2021-02-18 12:11:39,547-INFO: language model: is_character_based = 0, max_order = 5, dict_size = 400000
2021-02-18 12:11:39,620-INFO: end initializing scorer
2021-02-18 12:11:39,621-INFO: start tuning ...
W0218 12:11:45.212179 23717 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 11.1, Runtime API Version: 10.0
W0218 12:11:45.224212 23717 device_context.cc:260] device: 0, cuDNN Version: 8.0.
finish initing model from pretrained params from /root/DeepSpeech/examples/tiny/../..//models/librispeech
....................................................................................................................................................................................
Batch 0 [128/?], current opt (alpha, beta) = (3.200, 0.100),  min [wer] = 0.973516
finish initing model from pretrained params from /root/DeepSpeech/examples/tiny/../..//models/librispeech
....................................................................................................................................................................................
Batch 1 [256/?], current opt (alpha, beta) = (3.200, 0.150),  min [wer] = 0.972130
finish initing model from pretrained params from /root/DeepSpeech/examples/tiny/../..//models/librispeech
....................................................................................................................................................................................
Batch 2 [384/?], current opt (alpha, beta) = (3.200, 0.150),  min [wer] = 0.975304
finish initing model from pretrained params from /root/DeepSpeech/examples/tiny/../..//models/librispeech
....................................................................................................................................................................................
Batch 3 [512/?], current opt (alpha, beta) = (3.200, 0.150),  min [wer] = 0.974737
finish initing model from pretrained params from /root/DeepSpeech/examples/tiny/../..//models/librispeech
....................................................................................................................................................................................
Batch 4 [640/?], current opt (alpha, beta) = (3.200, 0.150),  min [wer] = 0.977027
finish initing model from pretrained params from /root/DeepSpeech/examples/tiny/../..//models/librispeech
....................................................................................................................................................................................
Batch 5 [768/?], current opt (alpha, beta) = (3.200, 0.150),  min [wer] = 0.976478
finish initing model from pretrained params from /root/DeepSpeech/examples/tiny/../..//models/librispeech
....................................................................................................................................................................................
Batch 6 [896/?], current opt (alpha, beta) = (3.200, 0.150),  min [wer] = 0.974615
finish initing model from pretrained params from /root/DeepSpeech/examples/tiny/../..//models/librispeech
....................................................................................................................................................................................
Batch 7 [1024/?], current opt (alpha, beta) = (3.200, 0.150),  min [wer] = 0.974513
finish initing model from pretrained params from /root/DeepSpeech/examples/tiny/../..//models/librispeech
....................................................................................................................................................................................
Batch 8 [1152/?], current opt (alpha, beta) = (3.200, 0.100),  min [wer] = 0.976047
finish initing model from pretrained params from /root/DeepSpeech/examples/tiny/../..//models/librispeech
....................................................................................................................................................................................
Batch 9 [1280/?], current opt (alpha, beta) = (3.200, 0.100),  min [wer] = 0.975835
finish initing model from pretrained params from /root/DeepSpeech/examples/tiny/../..//models/librispeech
....................................................................................................................................................................................
Batch 10 [1408/?], current opt (alpha, beta) = (3.200, 0.100),  min [wer] = 0.975548
./local/run_tune.sh: line 30: 23717 Killed                  CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -u $MAIN_ROOT/tools/tune.py --num_batches=-1 --batch_size=128 --beam_size=500 --num_proc_bsearch=12 --num_conv_layers=2 --num_rnn_layers=3 --rnn_layer_size=2048 --num_alphas=45 --num_betas=8 --alpha_from=1.0 --alpha_to=3.2 --beta_from=0.1 --beta_to=0.45 --cutoff_prob=1.0 --cutoff_top_n=40 --use_gru=False --use_gpu=True --share_rnn_weights=True --tune_manifest="data/manifest.dev-clean" --mean_std_path="data/mean_std.npz" --vocab_path="data/vocab.txt" --model_path="$MAIN_ROOT/models/librispeech" --lang_model_path="$MAIN_ROOT/models/lm/common_crawl_00.prune01111.trie.klm" --error_rate_type="wer" --specgram_type="linear"
Failed in tuning!

============

### bash run.sh

Unpacking /root/DeepSpeech/examples/aishell/../..//dataset/aishell/data_aishell/wav/S0598.tar.gz ...
Creating manifest data/manifest ...
============  Configuration Arguments ============
count_threshold: 0
manifest_paths: ['data/manifest.train', 'data/manifest.dev']
vocab_path: data/vocab.txt
================================================----
============  Configuration Arguments ============
manifest_path: data/manifest.train
num_samples: 2000
output_path: data/mean_std.npz
specgram_type: linear
================================================----
Aishell data preparation done.
Download language model ...
--2021-02-18 16:21:42--  https://deepspeech.bj.bcebos.com/zh_lm/zh_giga.no_cna_cmn.prune01244.klm
Resolving deepspeech.bj.bcebos.com (deepspeech.bj.bcebos.com)... 2409:8c00:6c21:10ad:0:ff:b00e:67d, 220.181.33.43, 220.181.33.44
Connecting to deepspeech.bj.bcebos.com (deepspeech.bj.bcebos.com)|2409:8c00:6c21:10ad:0:ff:b00e:67d|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2953395058 (2.8G) [application/octet-stream]
Saving to: './zh_giga.no_cna_cmn.prune01244.klm'

./zh_giga.no_cna_cmn.prune01244. 100%[=======================================================>]   2.75G  27.7MB/s    in 1m 45s  

2021-02-18 16:23:28 (26.7 MB/s) - './zh_giga.no_cna_cmn.prune01244.klm' saved [2953395058/2953395058]

Download Aishell model ...
--2021-02-18 16:23:34--  https://deepspeech.bj.bcebos.com/mandarin_models/aishell_model_fluid.tar.gz
Resolving deepspeech.bj.bcebos.com (deepspeech.bj.bcebos.com)... 2409:8c00:6c21:10ad:0:ff:b00e:67d, 220.181.33.44, 220.181.33.43
Connecting to deepspeech.bj.bcebos.com (deepspeech.bj.bcebos.com)|2409:8c00:6c21:10ad:0:ff:b00e:67d|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 227293290 (217M) [application/x-gzip]
Saving to: './aishell_model_fluid.tar.gz'

./aishell_model_fluid.tar.gz     100%[=======================================================>] 216.76M  27.2MB/s    in 12s     

2021-02-18 16:23:46 (18.7 MB/s) - './aishell_model_fluid.tar.gz' saved [227293290/227293290]

mean_std.npz
README.md
vocab.txt
params.pdparams
============  Configuration Arguments ============
alpha: 2.6
batch_size: 128
beam_size: 300
beta: 5.0
cutoff_prob: 0.99
cutoff_top_n: 40
decoding_method: ctc_beam_search
error_rate_type: cer
lang_model_path: /root/DeepSpeech/examples/aishell/../..//models/lm/zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: /root/DeepSpeech/examples/aishell/../..//models/aishell/mean_std.npz
model_path: /root/DeepSpeech/examples/aishell/../..//models/aishell
num_conv_layers: 2
num_proc_bsearch: 8
num_rnn_layers: 3
rnn_layer_size: 1024
share_rnn_weights: 0
specgram_type: linear
test_manifest: data/manifest.test
use_gpu: 1
use_gru: 1
vocab_path: /root/DeepSpeech/examples/aishell/../..//models/aishell/vocab.txt
================================================----
2021-02-18 16:23:50,817-INFO: begin to initialize the external scorer for decoding
2021-02-18 16:23:51,138-INFO: language model: is_character_based = 1, max_order = 5, dict_size = 0
2021-02-18 16:23:51,138-INFO: end initializing scorer
2021-02-18 16:23:51,138-INFO: start evaluation ...
W0218 16:23:55.017011  4562 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 11.1, Runtime API Version: 10.0
W0218 16:23:55.025905  4562 device_context.cc:260] device: 0, cuDNN Version: 8.0.
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (128/?) = 0.055526
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (256/?) = 0.051899
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (384/?) = 0.052061
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (512/?) = 0.056111
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (640/?) = 0.053693
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (768/?) = 0.055531
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (896/?) = 0.056642
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (1024/?) = 0.058581
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (1152/?) = 0.058872
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (1280/?) = 0.059066
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (1408/?) = 0.060236
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (1536/?) = 0.063794
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (1664/?) = 0.067118
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (1792/?) = 0.070420
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (1920/?) = 0.069857
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (2048/?) = 0.068976
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (2176/?) = 0.068703
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (2304/?) = 0.068002
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (2432/?) = 0.066791
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (2560/?) = 0.066410
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (2688/?) = 0.067141
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (2816/?) = 0.067251
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (2944/?) = 0.068165
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (3072/?) = 0.068429
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (3200/?) = 0.068761
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (3328/?) = 0.069398
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (3456/?) = 0.070203
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (3584/?) = 0.071271
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (3712/?) = 0.073296
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (3840/?) = 0.074478
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (3968/?) = 0.076443
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (4096/?) = 0.075874
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (4224/?) = 0.075810
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (4352/?) = 0.075598
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (4480/?) = 0.076835
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (4608/?) = 0.078134
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (4736/?) = 0.079075
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (4864/?) = 0.078314
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (4992/?) = 0.077751
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (5120/?) = 0.077168
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (5248/?) = 0.076967
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (5376/?) = 0.076557
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (5504/?) = 0.075942
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (5632/?) = 0.075414
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (5760/?) = 0.075584
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (5888/?) = 0.076243
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (6016/?) = 0.077038
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (6144/?) = 0.078038
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (6272/?) = 0.079831
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (6400/?) = 0.081442
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (6528/?) = 0.082090
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (6656/?) = 0.081777
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (6784/?) = 0.081388
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (6912/?) = 0.081175
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (7040/?) = 0.080895
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (7168/?) = 0.080448
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell
Error rate [cer] (7176/?) = 0.080447
Final error rate [cer] (7176/7176) = 0.080447
2021-02-18 16:54:37,277-INFO: finish evaluation
Download language model ...
./zh_giga.no_cna_cmn.prune01244.klm already exists, download skipped.
Download Aishell model ...
./aishell_model_fluid.tar.gz already exists, download skipped.
mean_std.npz
README.md
vocab.txt
params.pdparams
============  Configuration Arguments ============
alpha: 2.6
beam_size: 300
beta: 5.0
cutoff_prob: 0.99
cutoff_top_n: 40
decoding_method: ctc_beam_search
error_rate_type: cer
infer_manifest: data/manifest.test
lang_model_path: /root/DeepSpeech/examples/aishell/../..//models/lm/zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: /root/DeepSpeech/examples/aishell/../..//models/aishell/mean_std.npz
model_path: /root/DeepSpeech/examples/aishell/../..//models/aishell
num_conv_layers: 2
num_proc_bsearch: 8
num_rnn_layers: 3
num_samples: 10
rnn_layer_size: 1024
share_rnn_weights: 0
specgram_type: linear
use_gpu: 0
use_gru: 1
vocab_path: /root/DeepSpeech/examples/aishell/../..//models/aishell/vocab.txt
================================================----
2021-02-18 16:54:45,732-INFO: begin to initialize the external scorer for decoding
2021-02-18 16:54:45,823-INFO: language model: is_character_based = 1, max_order = 5, dict_size = 0
2021-02-18 16:54:45,823-INFO: end initializing scorer
2021-02-18 16:54:45,823-INFO: start inference ...
finish initing model from pretrained params from /root/DeepSpeech/examples/aishell/../..//models/aishell

Target Transcription: 维护正常的市场价格秩序
Output Transcription: 维护正常的市场价格秩序
Current error rate [cer] = 0.000000

Target Transcription: 研究者们选取了一些年龄大的跑者作为研究对象
Output Transcription: 研究者们选取了一些年龄大的跑者作为研究对象
Current error rate [cer] = 0.000000

Target Transcription: 在经济下行压力加大的背景下
Output Transcription: 在经济下行压力加大的背景下
Current error rate [cer] = 0.000000

Target Transcription: 公司已将原有的直销模式改为经销模式
Output Transcription: 公司已将原有的直销模式改为经销模式
Current error rate [cer] = 0.000000

Target Transcription: 记者从首都机场公安分局航站区派出所获悉
Output Transcription: 记者从首都机场公安分局行战区派出所获悉
Current error rate [cer] = 0.105263

Target Transcription: 年龄大跑者的步幅明显短于年轻人
Output Transcription: 年龄大跑者的不服明显短于年轻人
Current error rate [cer] = 0.133333

Target Transcription: 影片将在二零一五年一月在慕尼黑正式开机
Output Transcription: 影片将在二零一五年一月三目一黑正式开机
Current error rate [cer] = 0.157895

Target Transcription: 在市场整体从高速增长进入中高速增长区间的同时
Output Transcription: 在市场整体从高速增长进入中高速增长区间的同时
Current error rate [cer] = 0.000000

Target Transcription: 成功处置深航机上纵火事件
Output Transcription: 成功处置深航机上作火事件
Current error rate [cer] = 0.083333

Target Transcription: 一线城市签约十七万套
Output Transcription: 一线城市签约十七万套
Current error rate [cer] = 0.000000
2021-02-18 16:54:57,788-INFO: finish inference
============  Configuration Arguments ============
augment_conf_path: /root/DeepSpeech/examples/aishell/../..//conf/augmentation.config
batch_size: 64
dev_manifest: data/manifest.dev
init_from_pretrained_model: None
is_local: 1
learning_rate: 0.0005
max_duration: 27.0
mean_std_path: data/mean_std.npz
min_duration: 0.0
num_conv_layers: 2
num_epoch: 50
num_iter_print: 100
num_rnn_layers: 3
num_samples: 120000
output_model_dir: ./checkpoints
rnn_layer_size: 1024
save_epoch: 1
share_rnn_weights: 0
shuffle_method: batch_shuffle_clipped
specgram_type: linear
test_off: 0
train_manifest: data/manifest.train
use_gpu: 1
use_gru: 1
use_sortagrad: 1
vocab_path: data/vocab.txt
================================================----
W0218 16:54:59.143281 14427 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 11.1, Runtime API Version: 10.0
W0218 16:54:59.152488 14427 device_context.cc:260] device: 0, cuDNN Version: 8.0.
epoch: 0, batch: 0, train loss: 418.396118

epoch: 0, batch: 100, train loss: 62.416603

epoch: 0, batch: 200, train loss: 63.825356

epoch: 0, batch: 300, train loss: 54.420654

epoch: 0, batch: 400, train loss: 37.008553

epoch: 0, batch: 500, train loss: 26.452053

epoch: 0, batch: 600, train loss: 24.803284

epoch: 0, batch: 700, train loss: 23.048244

epoch: 0, batch: 800, train loss: 21.241261

W0218 17:14:01.788877 14487 operator.cc:187] warpctc raises an exception paddle::memory::allocation::BadAlloc, 

================================================
C++ Call Stacks (More useful to developers):
================================================
0   std::string paddle::platform::GetTraceBackString<std::string>(std::string&&, char const*, int)
1   paddle::memory::allocation::CUDAAllocator::AllocateImpl(unsigned long)
2   paddle::memory::allocation::AlignedAllocator::AllocateImpl(unsigned long)
3   paddle::memory::allocation::AutoGrowthBestFitAllocator::AllocateImpl(unsigned long)
4   paddle::memory::allocation::Allocator::Allocate(unsigned long)
5   paddle::memory::allocation::RetryAllocator::AllocateImpl(unsigned long)
6   paddle::memory::allocation::AllocatorFacade::Alloc(paddle::platform::Place const&, unsigned long)
7   paddle::memory::Alloc(paddle::platform::Place const&, unsigned long)
8   paddle::memory::Alloc(paddle::platform::DeviceContext const&, unsigned long)
9   paddle::framework::Tensor paddle::framework::ExecutionContext::AllocateTmpTensor<float, paddle::platform::CUDADeviceContext>(paddle::framework::DDim const&, paddle::platform::CUDADeviceContext const&) const
10  paddle::operators::WarpCTCFunctor<paddle::platform::CUDADeviceContext>::operator()(paddle::framework::ExecutionContext const&, float const*, float*, int const*, int const*, int const*, unsigned long, unsigned long, unsigned long, float*)
11  paddle::operators::WarpCTCKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
12  std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::WarpCTCKernel<paddle::platform::CUDADeviceContext, float> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
13  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
14  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
15  paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
16  paddle::framework::details::ComputationOpHandle::RunImpl()
17  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
18  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
19  std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
20  std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
21  ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

========================
Error Message Summary:
========================
ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 142.958496MB memory on GPU 0, available memory is only 24.562500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 at (/paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:69)
F0218 17:14:01.791173 14487 exception_holder.h:37] std::exception caught, 

================================================
C++ Call Stacks (More useful to developers):
================================================
0   std::string paddle::platform::GetTraceBackString<std::string>(std::string&&, char const*, int)
1   paddle::memory::allocation::CUDAAllocator::AllocateImpl(unsigned long)
2   paddle::memory::allocation::AlignedAllocator::AllocateImpl(unsigned long)
3   paddle::memory::allocation::AutoGrowthBestFitAllocator::AllocateImpl(unsigned long)
4   paddle::memory::allocation::Allocator::Allocate(unsigned long)
5   paddle::memory::allocation::RetryAllocator::AllocateImpl(unsigned long)
6   paddle::memory::allocation::AllocatorFacade::Alloc(paddle::platform::Place const&, unsigned long)
7   paddle::memory::Alloc(paddle::platform::Place const&, unsigned long)
8   paddle::memory::Alloc(paddle::platform::DeviceContext const&, unsigned long)
9   paddle::framework::Tensor paddle::framework::ExecutionContext::AllocateTmpTensor<float, paddle::platform::CUDADeviceContext>(paddle::framework::DDim const&, paddle::platform::CUDADeviceContext const&) const
10  paddle::operators::WarpCTCFunctor<paddle::platform::CUDADeviceContext>::operator()(paddle::framework::ExecutionContext const&, float const*, float*, int const*, int const*, int const*, unsigned long, unsigned long, unsigned long, float*)
11  paddle::operators::WarpCTCKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
12  std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::WarpCTCKernel<paddle::platform::CUDADeviceContext, float> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
13  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
14  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
15  paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
16  paddle::framework::details::ComputationOpHandle::RunImpl()
17  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
18  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
19  std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
20  std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
21  ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

========================
Error Message Summary:
========================
ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 142.958496MB memory on GPU 0, available memory is only 24.562500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 at (/paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:69)
*** Check failure stack trace: ***
    @     0x7f0a4b55676d  google::LogMessage::Fail()
    @     0x7f0a4b55a21c  google::LogMessage::SendToLog()
    @     0x7f0a4b556293  google::LogMessage::Flush()
    @     0x7f0a4b55b72e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f0a4e6acec8  paddle::framework::details::ExceptionHolder::Catch()
    @     0x7f0a4e74808e  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync()
    @     0x7f0a4e745a2f  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp()
    @     0x7f0a4e745cf4  _ZNSt17_Function_handlerIFvvESt17reference_wrapperISt12_Bind_simpleIFS1_ISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS6_12OpHandleBaseESt6atomicIiESt4hashISA_ESt8equal_toISA_ESaISt4pairIKSA_SC_EEESA_RKSt10shared_ptrINS5_13BlockingQueueImEEEEUlvE_vEEEvEEEE9_M_invokeERKSt9_Any_data
    @     0x7f0a4b5b3c33  std::_Function_handler<>::_M_invoke()
    @     0x7f0a4b3b11b7  std::__future_base::_State_base::_M_do_set()
    @     0x7f0b0ba3a997  __pthread_once_slow
    @     0x7f0a4e741ec2  _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS4_12OpHandleBaseESt6atomicIiESt4hashIS8_ESt8equal_toIS8_ESaISt4pairIKS8_SA_EEES8_RKSt10shared_ptrINS3_13BlockingQueueImEEEEUlvE_vEESaIiEFvvEE6_M_runEv
    @     0x7f0a4b3b3614  _ZZN10ThreadPoolC1EmENKUlvE_clEv
    @     0x7f0a89db9421  execute_native_thread_routine_compat
    @     0x7f0b0ba32fa3  start_thread
    @     0x7f0b0b9634df  clone
    @              (nil)  (unknown)
./local/run_train.sh: line 33: 14427 Aborted                 CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python3 -u ${MAIN_ROOT}/train.py --batch_size=64 --num_epoch=50 --num_conv_layers=2 --num_rnn_layers=3 --rnn_layer_size=1024 --num_iter_print=100 --save_epoch=1 --num_samples=120000 --learning_rate=5e-4 --max_duration=27.0 --min_duration=0.0 --test_off=False --use_sortagrad=True --use_gru=True --use_gpu=True --is_local=True --share_rnn_weights=False --train_manifest="data/manifest.train" --dev_manifest="data/manifest.dev" --mean_std_path="data/mean_std.npz" --vocab_path="data/vocab.txt" --output_model_dir="./checkpoints" --augment_conf_path="${MAIN_ROOT}/conf/augmentation.config" --specgram_type="linear" --shuffle_method="batch_shuffle_clipped"
Failed in training!
Download language model ...
./zh_giga.no_cna_cmn.prune01244.klm already exists, download skipped.
============  Configuration Arguments ============
alpha: 2.6
batch_size: 128
beam_size: 300
beta: 5.0
cutoff_prob: 0.99
cutoff_top_n: 40
decoding_method: ctc_beam_search
error_rate_type: cer
lang_model_path: /root/DeepSpeech/examples/aishell/../..//models/lm/zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: data/mean_std.npz
model_path: checkpoints/step_final
num_conv_layers: 2
num_proc_bsearch: 8
num_rnn_layers: 3
rnn_layer_size: 1024
share_rnn_weights: 0
specgram_type: linear
test_manifest: data/manifest.test
use_gpu: 1
use_gru: 1
vocab_path: data/vocab.txt
================================================----
2021-02-18 17:14:08,242-INFO: begin to initialize the external scorer for decoding
2021-02-18 17:14:08,423-INFO: language model: is_character_based = 1, max_order = 5, dict_size = 0
2021-02-18 17:14:08,423-INFO: end initializing scorer
2021-02-18 17:14:08,423-INFO: start evaluation ...
W0218 17:14:09.493114 19569 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 11.1, Runtime API Version: 10.0
W0218 17:14:09.498034 19569 device_context.cc:260] device: 0, cuDNN Version: 8.0.
checkpoints/step_final
Traceback (most recent call last):
  File "/root/DeepSpeech/examples/aishell/../..//test.py", line 159, in <module>
    main()
  File "/root/DeepSpeech/examples/aishell/../..//test.py", line 155, in main
    evaluate()
  File "/root/DeepSpeech/examples/aishell/../..//test.py", line 123, in evaluate
    feeding_dict=data_generator.feeding)
  File "/root/DeepSpeech/model_utils/model.py", line 420, in infer_batch_probs
    self.init_from_pretrained_model(exe, infer_program)
  File "/root/DeepSpeech/model_utils/model.py", line 164, in init_from_pretrained_model
    raise Warning("The pretrained params do not exist.")
Warning: The pretrained params do not exist.
Failed in evaluation!
Download language model ...
./zh_giga.no_cna_cmn.prune01244.klm already exists, download skipped.
============  Configuration Arguments ============
alpha: 2.6
beam_size: 300
beta: 5.0
cutoff_prob: 0.99
cutoff_top_n: 40
decoding_method: ctc_beam_search
error_rate_type: cer
infer_manifest: data/manifest.test
lang_model_path: /root/DeepSpeech/examples/aishell/../..//models/lm/zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: data/mean_std.npz
model_path: checkpoints/step_final
num_conv_layers: 2
num_proc_bsearch: 8
num_rnn_layers: 3
num_samples: 10
rnn_layer_size: 1024
share_rnn_weights: 0
specgram_type: linear
use_gpu: 1
use_gru: 1
vocab_path: data/vocab.txt
================================================----
2021-02-18 17:14:16,196-INFO: begin to initialize the external scorer for decoding
2021-02-18 17:14:16,292-INFO: language model: is_character_based = 1, max_order = 5, dict_size = 0
2021-02-18 17:14:16,292-INFO: end initializing scorer
2021-02-18 17:14:16,292-INFO: start inference ...
W0218 17:14:16.331327 19689 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 11.1, Runtime API Version: 10.0
W0218 17:14:16.332828 19689 device_context.cc:260] device: 0, cuDNN Version: 8.0.
checkpoints/step_final
Traceback (most recent call last):
  File "/root/DeepSpeech/examples/aishell/../..//infer.py", line 159, in <module>
    main()
  File "/root/DeepSpeech/examples/aishell/../..//infer.py", line 155, in main
    infer()
  File "/root/DeepSpeech/examples/aishell/../..//infer.py", line 131, in infer
    feeding_dict=data_generator.feeding)
  File "/root/DeepSpeech/model_utils/model.py", line 420, in infer_batch_probs
    self.init_from_pretrained_model(exe, infer_program)
  File "/root/DeepSpeech/model_utils/model.py", line 164, in init_from_pretrained_model
    raise Warning("The pretrained params do not exist.")
Warning: The pretrained params do not exist.
Failed in inference!

**Comment by zh794390558** [comment]
麻烦确保run.sh的脚本每一步都执行正确后再执行下一步，目前还没有做错误check，run.sh只是流程实例，可以分开执行的。

**Comment by zh794390558** [comment]
第一个问题是 ./local/run_tune.sh 可能占用大量的内存 OOM 了，或者是显存不够等。

**Comment by zh794390558** [comment]
第二个是训练的时候显存不够了
```
W0218 17:14:01.788877 14487 operator.cc:187] warpctc raises an exception paddle::memory::allocation::BadAlloc
Out of memory error on GPU 0. Cannot allocate 142.958496MB memory on GPU 0, available memory is only 24.562500MB
```

**Comment by monkeycc** [comment]
显存每次都是占用1-2G，就报错了
显存一共6G

我需要在哪里调整哪些参数吗


@zh794390558

**Comment by monkeycc** [comment]
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.45.01    Driver Version: 455.45.01    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 2060    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   57C    P2    32W /  N/A |   1062MiB /  5934MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      3329      C   python3                          1059MiB |
+-----------------------------------------------------------------------------+

```
@zh794390558

**Comment by monkeycc** [comment]
已经解决了，减小--batch_size即可

**Comment by zh794390558** [comment]
嗯嗯，一般显存爆的化，不该模型就只能减小batch了。
